import type { MetricHealth } from "../types";

/**
 * How each number on screen was produced.
 *
 * "Real versus generated" is the wrong axis, and the binary badge that encoded
 * it was hiding a more useful distinction. Checked against the corpus:
 *
 * - `demo-research-agent` holds 222 measurements computed by code from
 *   recorded spans, 50 returned by a live judge call, and 12 that failed with
 *   `AuthenticationError: 401`.
 * - `synthetic-showcase` holds 2400 rows with `raw_judge_output IS NULL` on
 *   every one of them. No judge was ever called for any of it.
 *
 * So a deterministic metric on the demo project is *more* trustworthy than a
 * judged one there — arithmetic over recorded spans has no model in the loop
 * and no ±0.2 swing. A two-state badge cannot say that. This module gives the
 * page the vocabulary to.
 */

export interface Provenance {
  /** Computed by code from recorded spans. No model, reproducible. */
  measured: number;
  /** A live model call read real output and returned a verdict. */
  judged: number;
  /** Drawn from a distribution by the generator. Never evidence. */
  authored: number;
  /** The judge errored or refused. Excluded from every score. */
  broken: number;
}

export function provenanceOf({
  metrics,
  generated,
}: {
  metrics: MetricHealth[];
  generated: boolean;
}): Provenance {
  const broken = metrics.reduce((sum, m) => sum + m.degraded, 0);

  if (generated) {
    // Every row, regardless of metric type. The generator writes scores for
    // deterministic metrics too — those numbers were authored just as much as
    // the judged ones, and grouping them as "measured" would be the exact
    // laundering this module exists to prevent.
    return {
      measured: 0,
      judged: 0,
      authored: metrics.reduce((sum, m) => sum + m.count, 0),
      broken,
    };
  }

  let measured = 0;
  let judged = 0;
  for (const m of metrics) {
    if (m.group === "quality") judged += m.count;
    else measured += m.count;
  }
  return { measured, judged, authored: 0, broken };
}

/** One sentence naming what the figures on this screen actually are. */
export function provenanceSentence(p: Provenance): string {
  if (p.authored > 0) {
    return `All ${p.authored} figures on this screen were generated by a script, not produced by an agent. Scores are drawn from a distribution and no judge was ever called. Useful for reading the design; not evidence of anything.`;
  }

  const parts: string[] = [];
  if (p.measured > 0) {
    parts.push(
      `${p.measured} computed from recorded spans by code — no model in the loop`,
    );
  }
  if (p.judged > 0) {
    parts.push(`${p.judged} returned by a live judge call, each carrying its ±0.2 swing`);
  }
  if (parts.length === 0) return "Nothing has been measured in this window.";

  const broken =
    p.broken > 0
      ? ` A further ${p.broken} judge ${p.broken === 1 ? "call" : "calls"} errored or refused and ${p.broken === 1 ? "is" : "are"} excluded from every figure.`
      : "";
  return `${parts.join("; ")}.${broken}`;
}
